version: "3.8"

services:
  web:
    build: .
    container_name: sanke-ai
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5000
    command: flask run --host=0.0.0.0
    restart: always
networks:
  default:
    external: true
    name: tunnel
